import {useState,useEffect,type FormEvent} from 'react';
import {ArrowRight,EyeOff,BookOpen,Loader2} from 'lucide-react';
import {AVATARS} from '../../data/content';
import {Avatar3D} from '../common/Avatar3D';
import {GameRulesModal} from '../common/GameRulesModal';
interface Props{initialRoomCode?:string;onJoin:(code:string,name:string,avatarId:string)=>void;errorMessage?:string|null;isJoining?:boolean}
export function MobileJoin({initialRoomCode='',onJoin,errorMessage,isJoining}:Props){
 const [code,setCode]=useState(initialRoomCode),[name,setName]=useState(''),[avatar,setAvatar]=useState(AVATARS[0]),[rules,setRules]=useState(false);
 useEffect(()=>{setCode(initialRoomCode.toUpperCase());},[initialRoomCode]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!isJoining&&code.trim()&&name.trim())onJoin(code,name,avatar.id);};
 return <div className="join-screen"><div><span className="eyebrow">SEU CONVITE PARA A MANSÃO</span><h1>Qual é o seu<br/>disfarce?</h1><p>Escolha como os outros vão te conhecer.<br/>Sua verdadeira identidade fica em segredo.</p></div><form onSubmit={submit}>{errorMessage&&<div role="alert" className="error-banner">{errorMessage}</div>}<div><label htmlFor="input-mobile-room-code">CÓDIGO DA SALA</label><input id="input-mobile-room-code" className="code-input" maxLength={5} minLength={5} autoComplete="off" autoCapitalize="characters" spellCheck={false} value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))} placeholder="ABCDE" required/></div><div><label htmlFor="input-mobile-name">SEU APELIDO</label><input id="input-mobile-name" maxLength={15} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="Como vamos chamar você?" required/></div><div><label>ESCOLHA SUA MARCA</label><div className="avatar-options">{AVATARS.map(a=><button type="button" key={a.id} aria-label={a.name} aria-pressed={avatar.id===a.id} className={avatar.id===a.id?'selected':''} onClick={()=>setAvatar(a)}><Avatar3D avatar={a} size="md"/></button>)}</div></div><button id="btn-mobile-enter-room" className="button-primary" disabled={isJoining} type="submit">{isJoining?<Loader2 size={17} className="animate-spin"/>:null}{isJoining?'Entrando…':'Entrar na mansão'}<ArrowRight size={17}/></button></form><div className="join-foot"><span><EyeOff size={13} className="inline mr-1"/>Sem cadastro. Só segredos.</span><button className="button-quiet" onClick={()=>setRules(true)}><BookOpen size={14}/>Regras</button></div><GameRulesModal isOpen={rules} onClose={()=>setRules(false)}/></div>;
}
