import {useState,useEffect} from 'react';
import {Eye,EyeOff,ScanEye,Fingerprint,Shield,Check,MapPin} from 'lucide-react';
import type {Player} from '../../types';
import {MANSION_ROOMS} from '../../data/mansion';
interface Props{player:Player;onRevealComplete:()=>void;onSelectRoom?:(id:string)=>void;readyCount?:number;totalPlayers?:number}
export function MobileRoleReveal({player,onRevealComplete,onSelectRoom,readyCount=0,totalPlayers=1}:Props){
 const [visible,setVisible]=useState(false);
 useEffect(()=>{const hide=()=>setVisible(false);window.addEventListener('blur',hide);document.addEventListener('visibilitychange',hide);return()=>{window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',hide);};},[]);
 const killer=player.role==='ASSASSINO',detective=player.role==='DETETIVE';
 const Icon=killer?Eye:detective?ScanEye:Shield;
 return <div className="join-screen role-screen"><span className="eyebrow"><EyeOff size={14}/>DOCUMENTO CONFIDENCIAL</span><div><h1>Ninguém precisa<br/>saber quem você é.</h1><p>Proteja sua tela antes de abrir o documento. Você pode esconder sua identidade a qualquer momento.</p></div>{visible?<section className={`identity-document ${killer?'killer':detective?'detective':''}`}><Icon size={40} strokeWidth={1.2}/><span className="field-label">SUA VERDADEIRA IDENTIDADE</span><h2>{killer?'O infiltrado':detective?'O detetive':'Inocente'}</h2><p>{killer?'Ataque em segredo durante a noite. Invente um álibi e convença o grupo de que você é inocente.':'Observe quem passa por você. Faça tarefas e, na reunião, confronte os álibis para ajudar o detetive.'}</p>{detective&&<p>Você pode consultar os encontros de uma pessoa por noite. Só você pode formalizar a acusação. Se for eliminado, um inocente recebe o distintivo.</p>}<button className="button-quiet" onClick={()=>setVisible(false)}><EyeOff size={15}/>Esconder identidade</button></section>:<button className="identity-document sealed" id="fingerprint-hold-area" onClick={()=>setVisible(true)}><Fingerprint size={58} strokeWidth={1}/><strong>Abrir meu documento</strong><small>Somente você deve ver esta informação.</small></button>}<div><label><MapPin size={13} className="inline mr-1"/>SEU CÔMODO INICIAL</label><div className="role-room-options">{MANSION_ROOMS.map(r=><button key={r.id} className={player.currentRoomId===r.id?'selected':''} onClick={()=>onSelectRoom?.(r.id)}>{r.name.split(' ')[0]}</button>)}</div></div><button id="btn-confirm-role-ready" className="button-primary" disabled={player.hasRevealedRole} onClick={()=>{setVisible(false);onRevealComplete();}}><Check size={17}/>{player.hasRevealedRole?'Você está pronto':'Entendi meu papel. Estou pronto.'}</button><span className="secret-note">{readyCount} de {totalPlayers} convidados prontos</span></div>;
}
