import {EyeOff,ScanEye,Moon,Shield,Skull,Clock3,Footprints} from 'lucide-react';
import type {PrivatePlayerData,PublicGameState} from '../../types';
import {Mansion3DGridMap} from '../common/Mansion3DGridMap';
interface Props{privateData:PrivatePlayerData;publicState:PublicGameState;onKill:(id:string,room?:string,x?:number,y?:number)=>void;onMove?:(x:number,y:number,room?:string)=>void;onInvestigate?:(id:string)=>void}
export function MobileNightAction({privateData:d,publicState:s,onKill,onMove,onInvestigate}:Props){
 const p=d.player,killer=p.role==='ASSASSINO',detective=p.role==='DETETIVE';
 if(d.isNightVictim||!p.isAlive)return <div className="mobile-night eliminated-screen"><Skull size={52}/><span className="eyebrow">SEU SEGREDO CONTINUA AQUI</span><h1>Você foi eliminado.</h1><p>Guarde o que viu. Não revele o infiltrado aos outros jogadores.</p><span className="secret-note"><EyeOff size={15}/>Acompanhe o amanhecer no telão.</span></div>;
 return <div className="mobile-night"><header className="mobile-night-heading"><span className="eyebrow"><Moon size={14}/>NOITE {s.round}</span><span className="small-clock"><Clock3 size={14}/>{s.timerSeconds}s</span></header><div className={`role-strip ${killer?'killer':detective?'detective':'innocent'}`}><span>{killer?'O INFILTRADO':detective?'O DETETIVE':'INOCENTE'}</span><EyeOff size={15}/></div><h1>{killer?d.nightActionSubmitted?'Agora, desapareça.':'Escolha sua próxima jogada.':detective?'Nem todo rosto é inocente.':'Observe. E sobreviva.'}</h1><p className="night-objective">{killer?d.nightActionSubmitted?'O ataque foi confirmado. Afaste-se e prepare seu álibi.':'Aproxime-se de alguém para atacar. Você tem um ataque por noite.':detective?'Investigue uma pessoa em segredo nesta noite. Depois, convença o grupo.':'Explore a mansão. Lembre-se de quem cruzou seu caminho para o debate.'}</p><Mansion3DGridMap players={s.players} currentPlayerId={p.id} isKiller={killer} isNight canMove onMove={onMove} onKillTarget={killer&&!d.nightActionSubmitted?(id,x,y)=>onKill(id,undefined,x,y):undefined} compact/>
 {detective&&<section className="investigation-panel"><span className="eyebrow"><ScanEye size={14}/> INVESTIGAÇÃO PARTICULAR</span>{d.detectiveInvestigationResult?<p className="investigation-result">{d.detectiveInvestigationResult.resultText}</p>:<div className="suspect-options">{s.players.filter(v=>v.id!==p.id&&v.isAlive).map(v=><button disabled={d.hasUsedAbility} key={v.id} onClick={()=>onInvestigate?.(v.id)}>{v.name}<ScanEye size={14}/></button>)}</div>}</section>}
 <p className="secret-note"><EyeOff size={14}/>Só você deve ver esta tela. Qualquer um pode blefar.</p></div>;
}
